// Offscreen screenshot harness for the Dynamic Island README.
//
// Renders the REAL components (components/*.qml + Config.qml) against a neutral
// light background and saves one PNG per island state. Everything is mock data:
// no MPRIS, no dbus-monitor, no Wayland session and no real user content. Run it
// through tools/make-screenshots.sh, which documents the exact command line.
//
// The island is laid out at its logical size and grabbed at 2x through
// Item.grabToImage(callback, targetSize) so the PNGs are crisp.

import QtQuick
import ".."
import "../components"

Window {
    id: root

    // 2x output: the canvas is logical pixels, the grab doubles it.
    readonly property int pixelRatio: 2
    // Neutral margin around the island (>= 24 px so nothing is clipped).
    readonly property int pad: 28

    // Neutral demo content for the media mock. Empty albumArt makes the real
    // MediaView fall back to its built-in placeholder tile.
    property var mockMedia: QtObject {
        property bool available: true
        property bool playing: true
        property string title: "Sample Track"
        property string artist: "Demo Artist"
        property string albumArt: ""
        property real position: 42000
        property real duration: 180000
        property bool canGoNext: true
        property bool canGoPrevious: true
        // `playingChanged` and `availableChanged` are generated by the
        // properties above; the views/main.qml connect to them.
        signal metadataChanged()
        function playPause() {}
        function next() {}
        function previous() {}
    }

    // Neutral demo notification, using the keys NotificationView.qml reads.
    property var mockNotification: QtObject {
        property string appName: "Notifications"
        property string appIcon: "dialog-information"
        property string imagePath: ""
        property string summary: "Standup in 5 minutes"
        property string body: "The team standup starts soon."
        property int urgency: 1
        property int id: 0
    }

    // Mock settings backends, so the settings page renders all three rows.
    property var mockVolume: QtObject {
        property bool available: true
        property real volume: 0.65
        property bool muted: false
        function setVolume(v) {}
        function toggleMute() {}
    }

    property var mockBrightness: QtObject {
        property bool available: true
        property int percent: 80
        function setPercent(v) {}
    }

    property var mockBluetooth: QtObject {
        property bool available: true
        property bool powered: true
        property int connectedCount: 1
        function togglePower() {}
    }

    // State list. The order drives the overview grid (3 rows x 2 columns).
    property var states: []
    property int current: -1

    // Per-state canvas / island geometry, in logical pixels.
    property int canvasW: 400
    property int canvasH: 200

    visible: true
    color: "#00000000"
    flags: Qt.FramelessWindowHint
    width: canvasW
    height: canvasH

    function buildStates() {
        // A realistic page set for the expanded card (media + calendar +
        // settings + customize), with the notification page added when shown.
        var pages = ["media", "calendar", "settings", "customize"]
        return [
            { "id": "compact", "mode": "idle", "expanded": false, "page": "calendar",
              "pages": [], "w": Config.idleWidth, "h": Config.idleHeight },
            { "id": "media", "mode": "media", "expanded": true, "page": "media",
              "pages": pages, "w": Config.mediaExpandedWidth, "h": Config.mediaExpandedHeight },
            { "id": "notification", "mode": "notification", "expanded": true, "page": "notification",
              "pages": pages.concat(["notification"]),
              "w": Config.notificationExpandedWidth, "h": Config.notificationExpandedHeight },
            { "id": "calendar", "mode": "idle", "expanded": true, "page": "calendar",
              "pages": pages, "w": Config.mediaExpandedWidth, "h": Config.mediaExpandedHeight },
            { "id": "settings", "mode": "idle", "expanded": true, "page": "settings",
              "pages": pages, "w": Config.mediaExpandedWidth, "h": Config.mediaExpandedHeight },
            { "id": "customize", "mode": "idle", "expanded": true, "page": "customize",
              "pages": pages, "w": Config.customizeWidth, "h": Config.customizeHeight }
        ]
    }

    function applyState(index) {
        var state = states[index]
        island.mode = state.mode
        island.page = state.page
        island.pages = state.pages
        island.expanded = state.expanded
        root.canvasW = state.w + 2 * root.pad
        root.canvasH = state.h + Config.topPadding + 2 * root.pad
        stage.width = state.w
        stage.height = state.h + Config.topPadding
    }

    function grabCurrent() {
        var state = states[current]
        var target = Qt.size(root.canvasW * root.pixelRatio,
                             root.canvasH * root.pixelRatio)
        canvas.grabToImage(function(result) {
            if (!result) {
                console.log("SHOT_FAILED " + state.id)
                advance()
                return
            }
            var path = "docs/screenshots/" + state.id + ".png"
            var saved = result.saveToFile(path)
            console.log("SHOT " + state.id + " " + target.width + "x" + target.height
                        + (saved ? " saved" : " SAVE_FAILED") + " " + path)
            advance()
        }, target)
    }

    function advance() {
        current += 1
        if (current >= states.length) {
            console.log("ALL_DONE")
            Qt.quit()
            return
        }
        applyState(current)
        stepTimer.start()
    }

    // Soft neutral background; the island sits centered with even padding.
    Rectangle {
        id: canvas
        anchors.fill: parent
        gradient: Gradient {
            GradientStop { position: 0.0; color: "#EFEFF4" }
            GradientStop { position: 1.0; color: "#D9D9E0" }
        }

        // The island is placed in an exact-size stage so its parent-relative
        // anchors match the real window geometry.
        Item {
            id: stage
            anchors.horizontalCenter: parent.horizontalCenter
            anchors.top: parent.top
            anchors.topMargin: root.pad
            width: 0
            height: 0

            Island {
                id: island
                anchors.fill: parent
                media: root.mockMedia
                notification: root.mockNotification
                volume: root.mockVolume
                brightness: root.mockBrightness
                bluetooth: root.mockBluetooth
            }
        }
    }

    Component.onCompleted: {
        states = buildStates()
        // Let fonts and themed icons settle before the first grab.
        warmupTimer.start()
    }

    Timer {
        id: warmupTimer
        interval: 600
        onTriggered: {
            current = 0
            applyState(0)
            stepTimer.start()
        }
    }

    // Long enough for the size/radius morph (300 ms) and the 150 ms cross-fade
    // to finish before grabbing each state.
    Timer {
        id: stepTimer
        interval: 650
        onTriggered: grabCurrent()
    }
}
